"""add_multi_tenancy_models

Revision ID: 31eb3f74e5a3
Revises: a022c8946f0c
Create Date: 2026-01-09 00:43:12.215371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eb3f74e5a3'
down_revision: Union[str, None] = 'a022c8946f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('sub_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_organizations_id'), 'sub_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_sub_organizations_name'), 'sub_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_sub_organizations_organization_id'), 'sub_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sub_organizations_slug'), 'sub_organizations', ['slug'], unique=False)
    # Add columns as nullable first
    op.add_column('documents', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('sub_organization_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('category', sa.Enum('HR', 'SALES', 'LEGAL', 'OPS', 'GENERAL', name='documentcategory'), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=True))
    
    # For existing documents, we need to set a default organization_id
    # Create a default organization for existing data (only if it doesn't exist)
    connection = op.get_bind()
    
    # Check if default organization exists
    result = connection.execute(sa.text("SELECT id FROM organizations WHERE slug = 'default' LIMIT 1"))
    default_org_id = result.scalar()
    
    if not default_org_id:
        # Create default organization
        connection.execute(sa.text("""
            INSERT INTO organizations (name, slug, description, is_active, created_at, updated_at)
            VALUES ('Default Organization', 'default', 'Default organization for existing data', true, NOW(), NOW())
        """))
        # Get the ID
        result = connection.execute(sa.text("SELECT id FROM organizations WHERE slug = 'default' LIMIT 1"))
        default_org_id = result.scalar()
    
    if default_org_id:
        # Update existing documents with default organization
        connection.execute(sa.text(f"UPDATE documents SET organization_id = {default_org_id} WHERE organization_id IS NULL"))
    
    # Now make organization_id non-nullable
    op.alter_column('documents', 'organization_id', nullable=False, existing_type=sa.Integer())
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_sub_organization_id'), 'documents', ['sub_organization_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'sub_organizations', ['sub_organization_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['id'])
    # Add role column with default value
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'ORG_ADMIN', 'SUB_ORG_ADMIN', 'USER', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sub_organization_id', sa.Integer(), nullable=True))
    
    # Set default role for existing users based on is_admin flag
    op.execute(sa.text("UPDATE users SET role = 'SUPER_ADMIN' WHERE is_admin = true AND role IS NULL"))
    op.execute(sa.text("UPDATE users SET role = 'USER' WHERE is_admin = false AND role IS NULL"))
    
    # Set organization_id for existing users to default organization
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM organizations WHERE slug = 'default' LIMIT 1"))
    default_org_id = result.scalar()
    
    if default_org_id:
        op.execute(sa.text(f"UPDATE users SET organization_id = {default_org_id} WHERE organization_id IS NULL AND role != 'SUPER_ADMIN'"))
    
    # Now make role non-nullable
    op.alter_column('users', 'role', nullable=False, existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'ORG_ADMIN', 'SUB_ORG_ADMIN', 'USER', name='userrole'))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_sub_organization_id'), 'users', ['sub_organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'sub_organizations', ['sub_organization_id'], ['id'])
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_sub_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'sub_organization_id')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_sub_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'sub_organization_id')
    op.drop_column('documents', 'organization_id')
    op.drop_index(op.f('ix_sub_organizations_slug'), table_name='sub_organizations')
    op.drop_index(op.f('ix_sub_organizations_organization_id'), table_name='sub_organizations')
    op.drop_index(op.f('ix_sub_organizations_name'), table_name='sub_organizations')
    op.drop_index(op.f('ix_sub_organizations_id'), table_name='sub_organizations')
    op.drop_table('sub_organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###

