"""remove_slug_from_organizations

Revision ID: 41d6ef7310d5
Revises: 31eb3f74e5a3
Create Date: 2026-01-09 01:06:10.222395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41d6ef7310d5'
down_revision: Union[str, None] = '31eb3f74e5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_column('organizations', 'slug')
    op.drop_index(op.f('ix_sub_organizations_slug'), table_name='sub_organizations')
    op.drop_column('sub_organizations', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_organizations', sa.Column('slug', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_sub_organizations_slug'), 'sub_organizations', ['slug'], unique=False)
    op.add_column('organizations', sa.Column('slug', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###

