"""add_token_tracking_columns

Revision ID: a022c8946f0c
Revises: cddbdd06be1a
Create Date: 2026-01-08 10:13:25.057915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a022c8946f0c'
down_revision: Union[str, None] = 'cddbdd06be1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('chat_history', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('used_tokens', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE chat_history SET prompt_tokens = 0 WHERE prompt_tokens IS NULL")
    op.execute("UPDATE chat_history SET completion_tokens = 0 WHERE completion_tokens IS NULL")
    op.execute("UPDATE users SET used_tokens = 0 WHERE used_tokens IS NULL")
    
    # Now make columns non-nullable
    op.alter_column('chat_history', 'prompt_tokens',
                    existing_type=sa.Integer(),
                    nullable=False)
    op.alter_column('chat_history', 'completion_tokens',
                    existing_type=sa.Integer(),
                    nullable=False)
    op.alter_column('users', 'used_tokens',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'used_tokens')
    op.drop_column('chat_history', 'completion_tokens')
    op.drop_column('chat_history', 'prompt_tokens')
    # ### end Alembic commands ###

