"""Conversation Table Added

Revision ID: cddbdd06be1a
Revises: ff6b483cb770
Create Date: 2026-01-08 03:48:28.237944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'cddbdd06be1a'
down_revision: Union[str, None] = 'ff6b483cb770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if conversations table already exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()
    
    # Create conversations table if it doesn't exist
    if 'conversations' not in tables:
        op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
        op.create_index(op.f('ix_conversations_document_id'), 'conversations', ['document_id'], unique=False)
        op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
        op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
        op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    
    # Check if conversation_id column already exists
    chat_history_columns = [col['name'] for col in inspector.get_columns('chat_history')]
    
    # Add conversation_id column as nullable first if it doesn't exist
    if 'conversation_id' not in chat_history_columns:
        op.add_column('chat_history', sa.Column('conversation_id', sa.Integer(), nullable=True))
    
    # Migrate existing chat_history records to conversations
    # Group by user_id and document_id, create a conversation for each group
    connection = op.get_bind()
    
    # First, ensure all NULL conversation_id values are populated
    # This handles the case where the migration partially ran before
    
    # Check if there are any existing chat_history records with NULL conversation_id
    null_check = connection.execute(sa.text("SELECT COUNT(*) FROM chat_history WHERE conversation_id IS NULL"))
    null_count = null_check.fetchone()[0]
    
    if null_count > 0:
        # Get distinct user_id, document_id pairs that need conversations
        result = connection.execute(sa.text("""
            SELECT DISTINCT user_id, document_id 
            FROM chat_history 
            WHERE conversation_id IS NULL
        """))
        
        for row in result:
            user_id, document_id = row
            # Check if a conversation already exists for this user-document pair
            existing_conv = connection.execute(sa.text("""
                SELECT id FROM conversations 
                WHERE user_id = :user_id AND document_id = :document_id 
                LIMIT 1
            """), {"user_id": user_id, "document_id": document_id})
            existing_row = existing_conv.fetchone()
            
            if existing_row:
                conv_id = existing_row[0]
            else:
                # Create a conversation for this user-document pair
                connection.execute(sa.text("""
                    INSERT INTO conversations (user_id, document_id, title, created_at, updated_at)
                    VALUES (:user_id, :document_id, NULL, NOW(), NOW())
                """), {"user_id": user_id, "document_id": document_id})
                
                # Get the conversation ID we just created
                conv_result = connection.execute(sa.text("""
                    SELECT id FROM conversations 
                    WHERE user_id = :user_id AND document_id = :document_id 
                    ORDER BY id DESC LIMIT 1
                """), {"user_id": user_id, "document_id": document_id})
                conv_id = conv_result.fetchone()[0]
            
            # Update all chat_history records for this user-document pair
            connection.execute(sa.text("""
                UPDATE chat_history 
                SET conversation_id = :conv_id 
                WHERE user_id = :user_id AND document_id = :document_id AND conversation_id IS NULL
            """), {"conv_id": conv_id, "user_id": user_id, "document_id": document_id})
        
        # Verify all records have conversation_id
        final_null_check = connection.execute(sa.text("SELECT COUNT(*) FROM chat_history WHERE conversation_id IS NULL"))
        final_null_count = final_null_check.fetchone()[0]
        if final_null_count > 0:
            raise Exception(f"Migration failed: {final_null_count} chat_history records still have NULL conversation_id")
    
    # Now make conversation_id non-nullable
    op.alter_column('chat_history', 'conversation_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False)
    op.create_index(op.f('ix_chat_history_conversation_id'), 'chat_history', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'chat_history', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_index(op.f('ix_chat_history_conversation_id'), table_name='chat_history')
    op.alter_column('chat_history', 'conversation_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    op.drop_column('chat_history', 'conversation_id')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_document_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###

